name: Algolia DocSearch Scraper

on:
  push:
    branches:
      - main
env:
  APPLICATION_ID: ${{ secrets.ALGOLIA_APPLICATION_ID }}
  API_KEY: ${{ secrets.ALGOLIA_API_KEY }}
jobs:
  deploy:
    name: Run Algolia DocSearch Scraper
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Execute DocSearch Scraper

        run: |
          docker run \
          -e APPLICATION_ID -e API_KEY \
          -e CONFIG="$(cat .github/algolia-docsearch/config-docusaurus-v2.json)" \
          algolia/docsearch-scraper \
          --no-exit-on-warn --no-exit-on-error
  